version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: pg-ticketing
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticketing
    volumes:
      - pg_ticketing_data:/var/lib/postgresql/data

volumes:
  pg_ticketing_data:
